import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy — ogogog" };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <main className="max-w-2xl mx-auto px-4 py-12">
        <Link href="/browse" className="text-xs font-bold uppercase tracking-widest text-gray-700 hover:text-black mb-8 inline-block">← Browse</Link>
        <h1 className="text-3xl font-black uppercase tracking-tight text-black mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-700 mb-10">Last updated: April 2026</p>

        <div className="space-y-8 text-sm text-black leading-relaxed">
          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">1. What we collect</h2>
            <p>We collect your email address (for authentication), any profile information you choose to add (username, display name, location, social links), listings you create, messages you send, and collection items you add. We also collect standard server logs (IP addresses, request metadata) for security purposes.</p>
          </section>

          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">2. How we use it</h2>
            <p>Your data is used to operate the marketplace: displaying your listings and profile to other users, sending message notifications to your email, and maintaining your account. We do not sell your data to third parties. We do not run targeted advertising.</p>
          </section>

          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">3. Email</h2>
            <p>We send transactional emails only: account verification, password resets, and notifications when you receive a message on a listing. We do not send marketing emails. Transactional email is handled by Resend.</p>
          </section>

          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">4. Third-party services</h2>
            <p>We use Supabase (database and authentication), Vercel (hosting), and Resend (email). Each has their own privacy policy. Avatar images are generated by DiceBear and loaded from their CDN.</p>
          </section>

          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">5. Your rights</h2>
            <p>You can delete your account at any time by contacting us. Upon deletion we will remove your profile, listings, and messages from our database. Some data may remain in backups for up to 30 days.</p>
          </section>

          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">6. Cookies</h2>
            <p>We use a single session cookie to keep you logged in. No tracking cookies, no analytics cookies, no third-party ad cookies.</p>
          </section>

          <section>
            <h2 className="font-black uppercase tracking-widest text-xs mb-3">7. Contact</h2>
            <p>For privacy questions or data deletion requests: <a href="mailto:zgarage.toys@gmail.com" className="underline">zgarage.toys@gmail.com</a></p>
          </section>
        </div>
      </main>
    </div>
  );
}
